environment: prod

azure:
  subscription_id: "1679edc6-fa8e-4210-9607-7b4dfd048934"
  resource_group: "rg-calcifer-westeurope-001"
  location: "westeurope"

k8s:
  version: "1.34"
  pod_network_cidr: "10.244.0.0/16"

  local_kubeconfig_path: "inventory/my_custom_kubeconfig.yaml"

  # Complex list (not manageable via ENV)
  kernel_modules:
    - overlay
    - br_netfilter

  # Complex dictionary
  sysctl_params:
    net.bridge.bridge-nf-call-ip6tables: "1"
    net.bridge.bridge-nf-call-iptables: "1"
    net.ipv4.ip_forward: "1"
    fs.inotify.max_user_watches: "524288"
    fs.inotify.max_user_instances: "512"

  flux:
    enabled: true
    github_url: "ssh://git@github.com/dmgiangi/calcifer-gitops.git"
    branch: "main"
    cluster_path: "clusters/production"